SPRITE_SCALING_PLAYER = 6
SPRITE_SCALING_enemy = 6
SPRITE_SCALING_LASER = 6

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "Space Invaders"

MAX_PLAYER_BULLETS = 3

DEATH_PAUSE_TIME = 0.85

# This margin controls how close the enemy gets to the left or right side
# before reversing direction.
ENEMY_VERTICAL_MARGIN = 15
RIGHT_ENEMY_BORDER = SCREEN_WIDTH - ENEMY_VERTICAL_MARGIN
LEFT_ENEMY_BORDER = ENEMY_VERTICAL_MARGIN

# Game state
GAME_OVER = 1
PLAY_GAME = 0
